name: CI/CD Microservices with Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Auth Service
      - name: Build and push Auth service
        uses: docker/build-push-action@v6
        with:
          context: ./auth
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/auth-service:latest

      # Product Service
      - name: Build and push Product service
        uses: docker/build-push-action@v6
        with:
          context: ./product
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/product-service:latest

      # Order Service
      - name: Build and push Order service
        uses: docker/build-push-action@v6
        with:
          context: ./order
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/order-service:latest

      # API Gateway
      - name: Build and push API Gateway
        uses: docker/build-push-action@v6
        with:
          context: ./api-gateway
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
