name: CI/CD Microservices with Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Lấy code từ GitHub
      - name: Checkout source
        uses: actions/checkout@v3

      # 2. Đăng nhập Docker Hub TRƯỚC để tránh lỗi 503
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Thiết lập Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Build + Push từng service
      - name: Build and push Auth service
        uses: docker/build-push-action@v6
        with:
          context: ./auth
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
            ${{ secrets.DOCKER_USERNAME }}/auth-service:${{ github.run_number }}

      - name: Build and push Product service
        uses: docker/build-push-action@v6
        with:
          context: ./product
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/product-service:latest
            ${{ secrets.DOCKER_USERNAME }}/product-service:${{ github.run_number }}

      - name: Build and push Order service
        uses: docker/build-push-action@v6
        with:
          context: ./order
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/order-service:latest
            ${{ secrets.DOCKER_USERNAME }}/order-service:${{ github.run_number }}

      - name: Build and push API Gateway
        uses: docker/build-push-action@v6
        with:
          context: ./api-gateway
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
            ${{ secrets.DOCKER_USERNAME }}/api-gateway:${{ github.run_number }}
