version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - micro_network

  mymongodb:
    image: mongo:7.0
    container_name: mymongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - micro_network

  api-gateway:
    image: tandang2202/api-gateway:latest    
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3003:3003"
    depends_on:
      - auth
      - order
      - product
    networks:
      - micro_network

  auth:
    image: tandang2202/auth:latest           
    build: ./auth
    container_name: auth
    environment:
      - MONGODB_AUTH_URI=mongodb://mymongodb:27017/authdb
      - JWT_SECRET=mySuperSecretKey_22001005_Tan_@2025
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - mymongodb
      - rabbitmq
    ports:
      - "3001:3001"
    networks:
      - micro_network

  product:
    image: tandang2202/product:latest        
    build: ./product
    container_name: product
    environment:
      - MONGODB_PRODUCT_URI=mongodb://mymongodb:27017/productdb
      - JWT_SECRET=mySuperSecretKey_22001005_Tan_@2025
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - mymongodb
      - rabbitmq
    ports:
      - "3002:3002"
    networks:
      - micro_network

  order:
    image: tandang2202/order:latest         
    build: ./order
    container_name: order
    environment:
      - MONGODB_ORDER_URI=mongodb://mymongodb:27017/orderdb
      - JWT_SECRET=mySuperSecretKey_22001005_Tan_@2025
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - mymongodb
      - rabbitmq
    ports:
      - "3004:3004"
    networks:
      - micro_network
    command: sh -c "sleep 10 && npm start"

volumes:
  mongo_data:

networks:
  micro_network:
    driver: bridge
